# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-19 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('cashInHand', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='rawMaterialOrder',
            fields=[
                ('gatePass', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('recieved', models.BooleanField(default=False)),
            ],
        ),
    ]
