# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-05 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171219_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='order',
            name='mobile_number',
            field=models.IntegerField(default=91),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default='produc', max_length=50),
            preserve_default=False,
        ),
    ]
